### ISSUE TITLE
[OTHER] (P+) Refactor a Complex Function

### ISSUE THREAD

**Issue by dague1** [dague1/Java#11]
### What would you like to share?

Refactor at least one of the functions (per group member) with high
cyclomatic complexity to reduce it by at least 35 %

**Comment by dague1** [comment]
working on remove and divide now

**Comment by AliAsbai** [comment]
Working on regexRecursion with 2 params now

**Comment by arenbro** [comment]
Working on regexRecursion with 4 arguments.

**Comment by dague1** [comment]
Done
